/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardIaRouteImport } from './routes/dashboard.ia'
import { Route as DashboardFinanceiroRouteImport } from './routes/dashboard.financeiro'
import { Route as DashboardCrmRouteImport } from './routes/dashboard.crm'
import { Route as DashboardConversasRouteImport } from './routes/dashboard.conversas'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as DashboardCampanhasRouteImport } from './routes/dashboard.campanhas'
import { Route as DashboardAutomacoesRouteImport } from './routes/dashboard.automacoes'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard.agenda'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIaRoute = DashboardIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceiroRoute = DashboardFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCrmRoute = DashboardCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversasRoute = DashboardConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampanhasRoute = DashboardCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutomacoesRoute = DashboardAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/automacoes': typeof DashboardAutomacoesRoute
  '/dashboard/campanhas': typeof DashboardCampanhasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/conversas': typeof DashboardConversasRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/ia': typeof DashboardIaRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/automacoes': typeof DashboardAutomacoesRoute
  '/dashboard/campanhas': typeof DashboardCampanhasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/conversas': typeof DashboardConversasRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/ia': typeof DashboardIaRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/automacoes': typeof DashboardAutomacoesRoute
  '/dashboard/campanhas': typeof DashboardCampanhasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/conversas': typeof DashboardConversasRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/ia': typeof DashboardIaRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/agenda'
    | '/dashboard/analytics'
    | '/dashboard/automacoes'
    | '/dashboard/campanhas'
    | '/dashboard/configuracoes'
    | '/dashboard/conversas'
    | '/dashboard/crm'
    | '/dashboard/financeiro'
    | '/dashboard/ia'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/agenda'
    | '/dashboard/analytics'
    | '/dashboard/automacoes'
    | '/dashboard/campanhas'
    | '/dashboard/configuracoes'
    | '/dashboard/conversas'
    | '/dashboard/crm'
    | '/dashboard/financeiro'
    | '/dashboard/ia'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/agenda'
    | '/dashboard/analytics'
    | '/dashboard/automacoes'
    | '/dashboard/campanhas'
    | '/dashboard/configuracoes'
    | '/dashboard/conversas'
    | '/dashboard/crm'
    | '/dashboard/financeiro'
    | '/dashboard/ia'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ia': {
      id: '/dashboard/ia'
      path: '/ia'
      fullPath: '/dashboard/ia'
      preLoaderRoute: typeof DashboardIaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/financeiro': {
      id: '/dashboard/financeiro'
      path: '/financeiro'
      fullPath: '/dashboard/financeiro'
      preLoaderRoute: typeof DashboardFinanceiroRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crm': {
      id: '/dashboard/crm'
      path: '/crm'
      fullPath: '/dashboard/crm'
      preLoaderRoute: typeof DashboardCrmRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversas': {
      id: '/dashboard/conversas'
      path: '/conversas'
      fullPath: '/dashboard/conversas'
      preLoaderRoute: typeof DashboardConversasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campanhas': {
      id: '/dashboard/campanhas'
      path: '/campanhas'
      fullPath: '/dashboard/campanhas'
      preLoaderRoute: typeof DashboardCampanhasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/automacoes': {
      id: '/dashboard/automacoes'
      path: '/automacoes'
      fullPath: '/dashboard/automacoes'
      preLoaderRoute: typeof DashboardAutomacoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAutomacoesRoute: typeof DashboardAutomacoesRoute
  DashboardCampanhasRoute: typeof DashboardCampanhasRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardConversasRoute: typeof DashboardConversasRoute
  DashboardCrmRoute: typeof DashboardCrmRoute
  DashboardFinanceiroRoute: typeof DashboardFinanceiroRoute
  DashboardIaRoute: typeof DashboardIaRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAutomacoesRoute: DashboardAutomacoesRoute,
  DashboardCampanhasRoute: DashboardCampanhasRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardConversasRoute: DashboardConversasRoute,
  DashboardCrmRoute: DashboardCrmRoute,
  DashboardFinanceiroRoute: DashboardFinanceiroRoute,
  DashboardIaRoute: DashboardIaRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
